gql/pubspec.yaml

Coming from Artemis, `gql` dependency is not working due to some conflicts with `analyzer`->`flutter_test` dependency tree.
Although Artemis (and `gql`) are Dart-only libraries, it's best to be in sync with at least flutter beta branch.
This is conjunction with https://github.com/comigor/artemis/pull/35 should be enough to make both libraries work on `beta` branch.

Downgrade some gql dependencies

---

gql_dedupe_link/CHANGELOG.md
gql_dedupe_link/pubspec.yaml
gql_dedupe_link/test/gql_dedupe_link_test.dart
gql_example_cli/bin/main.dart
gql_example_cli/pubspec.yaml
gql_exec/CHANGELOG.md
gql_exec/lib/exec/operation.dart
gql_exec/lib/exec/request.dart
gql_exec/pubspec.yaml
gql_http_link/CHANGELOG.md
gql_http_link/pubspec.yaml
gql_http_link/test/gql_http_link_test.dart
gql_link/CHANGELOG.md
gql_link/lib/src/request_serializer.dart
gql_link/pubspec.yaml
gql_transform_link/CHANGELOG.md
gql_transform_link/example/gql_transform_link_example.dart
gql_transform_link/pubspec.yaml
gql_transform_link/test/gql_transform_link_test.dart

`Operation` is now a container of an operation in a document
designed to only be dependent on the GraphQL document.
`Request` is now a parameterized invocation of an `Operation`.

move `variables` from `Operation` to `Request`

---

gql_code_gen/lib/ast_builder.dart

closes #27
This implements a simple solution to #27 in a recursive fashion. It probably isn't the most elegant solution to the problem, but (I'm fairly sure) it handles nested imports without risk of an infinite loop due to a cycle.

Recursive #import inlining

---

gql_code_builder/lib/src/operation/data.dart

This PR updates the data_builder to call `toDouble` on fields that expect a `double`. This ensures that even if the data received is stored in the `data` map as an integer, it will still get returned as a `double`.

Ensure doubles are generated properly

---

gql_http_link/CHANGELOG.md
gql_http_link/lib/src/link.dart
gql_http_link/pubspec.yaml
gql_http_link/test/gql_http_link_test.dart

Create a dispose method on HttpLink to close the underlining http client.

Dispose the underlining http client

---

gql_code_builder/lib/src/common.dart
gql_code_builder/lib/src/operation/data.dart

Per https://github.com/gql-dart/gql/issues/40, this PR maps the operation to the appropriate type.

Allow mutation and subscription operations

---

gql/lib/src/validation/rules/unique_type_names.dart
gql/lib/src/validation/validator.dart
gql/test/validation/unique_type_names_test.dart

I saw your post on Reddit about these validation rules, and looked around the currently implemented 
validations and the reference implementation and came up with this. Hope this helps.
Closes https://github.com/gql-dart/gql/issues/5.

Implement UniqueTypeNames rule

---

gql/lib/src/validation/rules/unique_input_field_names.dart
gql/lib/src/validation/validator.dart
gql/test/validation/unique_input_field_names_test.dart

This adds the UniqueInputFieldNames validator. It required a few more tweaks to the original JS code, because as far as I can tell, there is no "enter" and "leave" hooks for the visitors (yet?). 
I also copied most of the test cases from the JS source to make sure that this implementation is complying with the reference.

Add UniqueInputFieldNames validator

---

gql_build/lib/src/ast_builder.dart
gql_build/lib/src/data_builder.dart
gql_build/lib/src/enum_builder.dart
gql_build/lib/src/fragment_builder.dart
gql_build/lib/src/input_builder.dart
gql_build/lib/src/op_builder.dart
gql_build/lib/src/req_builder.dart
gql_build/lib/src/scalar_builder.dart
gql_build/lib/src/schema_builder.dart
gql_build/lib/src/utils/reader.dart
gql_build/lib/src/var_builder.dart
gql_code_builder/lib/source.dart

- implement `SourceNode`
- read sources as a tree of source nodes instead of a flat concatenated document
- temporarily flatten source tree to document for backwards-compatibility

implement SourceNode

---

gql_build/CHANGELOG.md
gql_build/lib/src/data_builder.dart
gql_build/lib/src/utils/add_introspection.dart
gql_build/lib/src/var_builder.dart
gql_build/pubspec.yaml
gql_code_builder/CHANGELOG.md
gql_code_builder/lib/source.dart
gql_code_builder/pubspec.yaml

Fixes #73.
Looks like it was a very simple fix.

Remove duplicate ast imports

---

gql_websocket_link/lib/src/link.dart

Instantiate a default `SocketClientConfig` on `WSLink` to avoid "was called on null" errors.

Avoid WSLink config null error

---

links/gql_http_link/CHANGELOG.md
links/gql_http_link/lib/src/_utils.dart
links/gql_http_link/lib/src/link.dart
links/gql_http_link/pubspec.yaml
links/gql_http_link/test/gql_http_link_test.dart
links/gql_http_link/test/helpers.dart
links/gql_http_link/test/multipart_upload_test.dart
links/gql_websocket_link/README.md

This extracts the logic for multipart file upload and `useGETForQueries` from `graphql/client.dart`, with accompanying tests
**Major changes**:
* `useGetForQueries` argument to `HttpLink`
* using `http.Client.send` instead of `post`
* `HttpLink` stores `uri` as a `Uri`
* I reworked `HttpLink._serializeRequest` into an exception handling HOF to handle the different paths, but really I think `RequestSerializer` should have a generic `Serialized` type which is `http.BaseRequest` for `HttpLink`. Otherwise it can't really handle the serialization concern IMO
This addresses some of #57

Multipart File Upload and useGETForQueries support

---

links/gql_http_link/CHANGELOG.md
links/gql_http_link/lib/src/_utils.dart
links/gql_http_link/pubspec.yaml
links/gql_http_link/test/gql_http_link_test.dart
links/gql_link/CHANGELOG.md
links/gql_link/pubspec.yaml

* fix custom scalar support in http link (the assert just shouldn't have been there, probably after being moved)
* publish `gql_http_link==0.3.2`
* publish `gql_link==0.3.1` with better exception toStrings

Http link custom scalars

---

links/gql_exec/lib/src/operation.dart
links/gql_exec/pubspec.yaml

errors are hard to parse without having the actual operation printed.
@klavs On the other hand, maybe that's ok/desired so that the output is legible?

[gql_exec] Print operation

---

links/gql_dio_link/lib/src/dio_link.dart
links/gql_dio_link/test/gql_dio_link_test.dart

I've fixed an issue with the package that was adding twice the content-type header, thus causing the request to fail for graphql.
There's a discussion here for further details:
https://github.com/TarekkMA/gql_dio_link/issues/4

Fix triplicated content-type headers on gql_dio_link

---

gql/example/visit_types.dart
gql/lib/src/ast/ast.dart
gql/lib/src/ast/transformer.dart
gql/lib/src/language/printer.dart
gql/lib/src/operation/definitions/definitions.dart
gql/lib/src/operation/executable.dart
gql/lib/src/schema/definitions/base_types.dart
gql/lib/src/schema/definitions/definitions.dart
gql/lib/src/schema/schema.dart
gql/lib/src/validation/rules/unique_directive_names.dart
gql/lib/src/validation/rules/unique_enum_value_names.dart
gql/lib/src/validation/rules/unique_type_names.dart
gql/pubspec.yaml

This should get rid of the abuse of `!` operator.

avoid using nullable name where name is mandatory

---

cats/lib/src/cat_builder.dart

`yaml 3` has breaking change which require `sourceUrl` to be of type `Uri`
This PR fix it.

Use Uri.file(file.path) fixes breaking changes in yaml 3

---

links/gql_dio_link/CHANGELOG.md
links/gql_dio_link/lib/src/dio_link.dart
links/gql_dio_link/lib/src/exceptions.dart
links/gql_dio_link/pubspec.yaml
links/gql_dio_link/test/gql_dio_link_test.dart

Pass original exception also if http request fails with error status. Dio throws DioError if response status is in error range so this makes it possible to have that as original error and makes debugging easier.

gql_dio_link: Forward original exception on dio errors

---

links/gql_websocket_link/lib/src/link.dart

The assertion now checks if either one of the two values is null while the other is not which aligns with the given documentation. The previous assertion only checked if one of them is null. 
Took me quite some time to find the bug which was caused by a null URI in an isolate.

gql_websocket_link:  better (correct) assertion

---

README.md
links/gql_dio_link/README.md

some links were still referencing my old repo

Fix readme links

---

codegen/gql_code_builder/lib/src/built_class.dart
codegen/gql_code_builder/lib/src/schema/enum.dart
codegen/gql_code_builder/lib/src/utils/to_camel_case.dart
codegen/gql_code_builder/pubspec.yaml

Fix camel case inconsistency

---

links/gql_http_link/lib/src/link.dart
links/gql_http_link/test/gql_http_link_test.dart
links/gql_link/lib/src/link.dart
links/gql_websocket_link/lib/src/link.dart

This PR adds a canonical `dispose()` method to the `Link` class.
This includes a minor breaking change - `HttpLink`'s dispose method now returns a `Future<void>` instead of a `void`.

feat: add canonical dispose method on gql_link

---

links/gql_websocket_link/lib/src/link.dart
links/gql_websocket_link/lib/src/messages.dart
links/gql_websocket_link/test/gql_websocket_link_test.dart

Fixes [237](https://github.com/gql-dart/gql/issues/237) and [260](https://github.com/gql-dart/gql/issues/260). 
Improves on [278](https://github.com/gql-dart/gql/pull/278) to fix [260](https://github.com/gql-dart/gql/issues/260) by using `websocket_status.normalClosure` instead of `websocket_status.goingAway`to support web (replicated the issue and tested on a browser).
Hi, from the conversation in [237](https://github.com/gql-dart/gql/issues/237) I added `errors` and `extensions` field in `SubscriptionError`, the parsing checks if the error objects are of the right format for `ResponseParser.parseError`. The root (response) extensions are only passed if the payload could not be parsed as an error, since otherwise they would be duplicated in the `errors[0].extension` and …

[gql_websocket_link] Parse errors and extension in error message type use websocket_status.normalClosure

---

.github/workflows/publish_tag.yml

Publish packages when we create a tag, this is a copy of `publish_alpha` workflow and I just removed the `bump-alpha` step.

publish tag

---

.github/workflows/publish_release.yml

Publish the packages when we push to `release` branch. Same as `publish_alpha` workflow.

publish release branch

---

gql/lib/src/validation/rules/missing_fragment_definitions.dart
gql/lib/src/validation/validator.dart
gql/test/validation/missing_fragment_definition_test.dart

I added a rule that checks that all fragments are present for all fragment spreads within a document. This helps when validating an operation document.

add "missing fragment definition" validation rule

---

links/gql_websocket_link/CHANGELOG.md
links/gql_websocket_link/lib/src/link.dart
links/gql_websocket_link/pubspec.yaml

This is an approach to make connection tracking available to users of the `WebSocketLink`.
Instead of offering a callback one could also add a getter to make the `_connectionStateController`'s `stream` accessible, so that a user could directly `listen` to it.
I'd be happy about any comments.

link/websocket: Add connection state callback

---

codegen/end_to_end_test/lib/interfaces/hero_for_episode.data.gql.dart
codegen/gql_code_builder/lib/src/inline_fragment_classes.dart
codegen/gql_code_builder/lib/src/serializers/inline_fragment_serializer.dart

Release builds on web do code minification, this causes serialization issues when inline fragments are used. 
The InlineFragmentSerializer uses `toString()` on a type to compare to a graphql `__typename`. Unfortunately in minifed versions the `toString()` method on a dart Type returns a mangled class name and not the expected class name.

Union types in web release mode

---

links/gql_dio_link/pubspec.yaml

This fixes the error mentioned in https://github.com/gql-dart/gql/pull/324#issuecomment-1204051957
I also suggest adding `depend_on_referenced_packages` to the lints.
cc @knaeckeKami

Fix dependencies for gql_dio_link

---

links/gql_dio_link/lib/src/dio_link.dart
links/gql_dio_link/test/gql_dio_link_test.dart
links/gql_http_link/test/gql_http_link_test.dart

I've noticed that the `DioLink` wasn't working in all cases. It works now much more similar than the `HttpLink` with get requests, which was working for all cases I know of. While fixing this, I've made the test more extensive.

Fix Dio Link with get requests and add more tests

---

codegen/gql_build/lib/src/config.dart

Use string split/join with forward slash instead of path library to fix Windows builds on gql_build 0.4.1. Tested on Windows and MacOS. Path library on Windows outputs backslash which is later translated to %5C, causing Dart import statements to be the malformed, such as: `import 'package:test%5Capi%5Cgql%5Cschema%5C__generated__%5Cschema.schema.gql.dart'
as _i2;`
I can't seem to find a unit-test, so I've run it against my own schema on both Windows and MacOS.
I generally dislike removing 'path' library from code as @smkhalsa added it in https://github.com/gql-dart/gql/commit/3a10c83f6085e8ad903831a809d0274f0f4aecec for a reason I suspect. I'm just trying to fix windows builds for gql_build 0.4.1 without breaking something else in the process.
This attempts to fix …

fix windows build on gql_build 0.4.1

---

links/gql_exec/lib/src/http.dart

This is a first step towards fixing #361. After this is merged and release, I'll change the contexts in `gql_http_link` and `gql_dio_link` to be subclasses of the classes introduced in this PR. Therefore, it will be a non-breaking change. 
If you have any other ideas on how to introduce this in a non-breaking change, feel free to suggest them.

Add `BaseHttpLinkHeaders` and `BaseHttpLinkResponseContext` to gql_exec

---

.github/workflows/dart.yml

since graphiviz does not work deterministially, the svg check is useless

remove broken svg check

---

codegen/end_to_end_test/pubspec.yaml
codegen/gql_build/pubspec.yaml
codegen/gql_code_builder/pubspec.yaml
examples/gql_example_cli/pubspec.yaml
examples/gql_example_cli_github/pubspec.yaml
examples/gql_example_dio_link/pubspec.yaml
examples/gql_example_flutter/pubspec.yaml
examples/gql_example_http_auth_link/pubspec.yaml
gql/CHANGELOG.md
gql/pubspec.yaml
links/gql_dedupe_link/pubspec.yaml
links/gql_dio_link/CHANGELOG.md
links/gql_dio_link/pubspec.yaml
links/gql_error_link/CHANGELOG.md
links/gql_error_link/pubspec.yaml
links/gql_exec/CHANGELOG.md
links/gql_exec/pubspec.yaml
links/gql_http_link/CHANGELOG.md
links/gql_http_link/pubspec.yaml
links/gql_link/CHANGELOG.md
links/gql_link/pubspec.yaml
links/gql_transform_link/CHANGELOG.md
links/gql_transform_link/pubspec.yaml
links/gql_websocket_link/CHANGELOG.md
links/gql_websocket_link/pubspec.yaml

I would like to bump the version of the core packages of gql to 1.0.0.
I am aware that this might be an inconvenience for packages depending on gql packages because the jump to 1.0.0 is treated as a breaking change by pub.
However, they have been on 0.x version for a long time now, breaking changes are rare and I have been accused of using 
https://0ver.org/ based versioning ;)
@agent3bood @budde377 @vincenzopalazzo FYI

stable versions 1.0

---

codegen/gql_build/lib/gql_build.dart
codegen/gql_build/lib/src/data_builder.dart
codegen/gql_build/lib/src/utils/config.dart
codegen/gql_code_builder/lib/data.dart
codegen/gql_code_builder/lib/src/built_class.dart
codegen/gql_code_builder/lib/src/common.dart
codegen/gql_code_builder/lib/src/config/data_class_config.dart
codegen/gql_code_builder/lib/src/inline_fragment_classes.dart
codegen/gql_code_builder/lib/src/operation/data.dart
codegen/gql_code_builder/lib/src/when_extension.dart

Hi Team and especially @knaeckeKami,
There is an old issue in this library. Which is gql-dart/ferry#143, first reported at Jan, 2021.
I made this PR to address this issue again and share the working draft of a possible solution.
There can be many aspects making build slower, but here I focused on how `gql_code_builder` generates data models.
A code generation for GraphQL type class and built value class gets extremely slower as schema and query gets larger.
The main reasons for that I found:
- With **recursively nesting fragments**, the number of models generated grows exponentially.
- Even for a **single FragmentSpreadNode selection** that is identical to a fragment model already created, a builder will generate the same code just with a different name.
```graphql
query TestQuery { …
```

[gql_code_builder] optimize slow code generation to reduce build time as 10% of previous.

---

examples/gql_example_http_auth_link/lib/http_auth_link.dart

This PR will queue incoming requests during the token refresh process. The token refresh queue ensures that only one token refresh occurs at a time, preventing multiple concurrent refreshes.

[gql_example_http_auth_link] add request queuing while refreshing token

---

links/gql_dedupe_link/lib/gql_dedupe_link.dart
links/gql_dedupe_link/pubspec.yaml
links/gql_dedupe_link/test/gql_dedupe_link_test.dart

Dedupe link is an all or nothing solution at the moment, but in use it is likely you would want to dedupe queries, but not mutations, or possibly filter deduplication in some other granular way. This modification allows for devs to consider the incoming request and prevent deduplication if desired.

feat(dedupe_link): Add shouldDedupe option

---

codegen/end_to_end_test/lib/fragments/__generated__/fragment_with_scalar_var.var.gql.dart
codegen/end_to_end_test/lib/fragments/__generated__/hero_with_fragments.var.gql.dart
codegen/end_to_end_test/lib/fragments/__generated__/multiple_fragments.var.gql.dart
codegen/end_to_end_test/lib/scalars/__generated__/review_with_date.var.gql.dart
codegen/end_to_end_test/lib/variables/__generated__/create_review.var.gql.dart
codegen/end_to_end_test_tristate/lib/fragments/__generated__/hero_with_fragments.var.gql.dart
codegen/gql_build/pubspec.yaml
codegen/gql_code_builder/lib/src/required_vars_constructor.dart
codegen/gql_code_builder/lib/var.dart
codegen/gql_code_builder/pubspec.yaml

Hi @knaeckeKami!
Unfortunately I found a bug in my previous commit for the vars create factories 🙈 
Nullables were still required and types that were in the typeOverrides, were called with the `toBuilder()` function causing the compiler to fail for these files.
🙈 🙈 🙈 🤦 🤦 🤦 🙈🙈🙈
I fixed it on this branch and hoping we can merge this as a new bugfix version. Sorry for the initial oversight.
As for Ferry: Happy to open a PR making this new bugfix version a dependency if that helps you at all!
Thanks,
Florian!

chore(vars-builder-bugfix): Fixing nullables and type overrides for vars create factories

---

codegen/end_to_end_test/lib/graphql/__generated__/schema.ast.gql.dart
codegen/end_to_end_test/lib/graphql/__generated__/serializers.gql.dart
codegen/end_to_end_test/lib/graphql/__generated__/serializers.gql.g.dart
codegen/end_to_end_test/lib/graphql/schema.graphql
codegen/end_to_end_test/lib/variables/__generated__/list_argument.ast.gql.dart
codegen/end_to_end_test/lib/variables/__generated__/list_argument.data.gql.dart
codegen/end_to_end_test/lib/variables/__generated__/list_argument.data.gql.g.dart
codegen/end_to_end_test/lib/variables/__generated__/list_argument.req.gql.dart
codegen/end_to_end_test/lib/variables/__generated__/list_argument.req.gql.g.dart
codegen/end_to_end_test/lib/variables/__generated__/list_argument.var.gql.dart
codegen/end_to_end_test/lib/variables/__generated__/list_argument.var.gql.g.dart
codegen/end_to_end_test/lib/variables/list_argument.graphql
codegen/gql_code_builder/lib/src/required_vars_constructor.dart
links/gql_websocket_link/lib/src/messages.dart

Hi! 👋 
I've tried to use that feature [vars_create_factories](https://github.com/gql-dart/gql/pull/434) and I've encounter an issue with arguments being lists. The parameter of a factory requires a `BuiltList` that is assigned to `ListBuilder` and that is not allowed.
@caffeineflo I've found some solution. Not sure whether it's the best way, but it works for me. So if you could take a look 🙏

[gql_code_builder] fix: vars_create_factories handle BuiltList type

---

codegen/gql_tristate_value/lib/src/value.dart
codegen/gql_tristate_value/test/value_test.dart

Hey! 👋 
I've been lacking the option to send a value if it exists and not send any value (neither null) if not present.
~~EDIT: Converted to DRAFT, because it's not working yet.~~

#feat: Add value or absent option

---

codegen/end_to_end_test/build.yaml
codegen/end_to_end_test/lib/graphql/__generated__/schema.schema.gql.dart
codegen/end_to_end_test/test/schema/input_test.dart
codegen/end_to_end_test_tristate/build.yaml
codegen/end_to_end_test_tristate/lib/graphql/__generated__/schema.schema.gql.dart
codegen/gql_build/lib/gql_build.dart
codegen/gql_build/lib/src/schema_builder.dart
codegen/gql_code_builder/lib/schema.dart
codegen/gql_code_builder/lib/src/schema.dart
codegen/gql_code_builder/lib/src/schema/input.dart

Hello 👋 
it's the `create` factories guy again! 
Since we've been busy using the create factories we've added a while back, we noticed that we must have forgotten to apply the same factories to input types *doh* 
This makes it hard using the `create` factories/initializer very hard since input types are kinda necessary to be covered when your `Vars`/Inputs  go beyond simple value types.
This PR fixes that previous oversight and adds `create` factories to Input types.
I've added a unit test as well for completeness, but please let mw know if there are any questions on this! 
Thanks

chore(vars-create-input): Adding Create Factories to Input types

---

melos.yaml

I noticed that we actually don't use git-tags and that git-tags would actually make this workflow more complicated. So removing this option from the melos setup for now

fix: Adding --no-git-tag-version to melos bump version commands
