- .github/workflows/actions.yml
- gql/lib/src/ast/transformer.dart
- gql/lib/src/language/parser.dart
- gql/lib/src/validation/validating_visitor.dart
- gql_dedupe_link/example/gql_dedupe_link_example.dart
- gql_http_link/example/gql_http_link_example.dart
Add GitHub Actions PR checks to run `pub test` and linter on all packages.
> Add GitHub Actions PR checks

- gql_build/example/README.md
Per request [here](https://github.com/gql-dart/gql/pull/32#discussion_r368243880)
> fix example

- multipack/lib/commands/common.dart
- multipack/lib/commands/pubspec.dart
- multipack/lib/commands/pubspec/common.dart
- multipack/lib/commands/pubspec/hard_override.dart
- multipack/lib/commands/pubspec/override.dart
- multipack/pubspec.yaml
- relative override paths
- Windows support for override command
- hard override command override dependency field directly
> improve multipack

- gql/example/add_typenames.dart
- gql/example/visit_types.dart
- gql/lib/src/ast/ast.dart
- gql/lib/src/ast/visitor.dart
- gql/lib/src/validation/rules/lone_schema_definition.dart
- gql/lib/src/validation/rules/unique_directive_names.dart
- gql/lib/src/validation/rules/unique_enum_value_names.dart
- gql/lib/src/validation/rules/unique_field_definition_names.dart
- gql/lib/src/validation/rules/unique_operation_types.dart
- gql/test/scenarios_test.dart
- gql_build/lib/src/fragment_builder.dart
- gql_code_builder/lib/src/operation/data.dart
- gql_dedupe_link/test/gql_dedupe_link_test.dart
- gql_pedantic/CHANGELOG.md
- gql_pedantic/lib/analysis_options.yaml
- gql_pedantic/pubspec.yaml
- multipack/bin/main.dart
> Pedantic next

- gql_build/lib/src/ast_builder.dart
- gql_build/lib/src/utils/writer.dart
- gql_code_builder/lib/ast.dart
- gql_code_builder/lib/source.dart
- gql_example_cli/lib/find_pokemon.ast.gql.dart
- gql_example_flutter/lib/src/all_pokemon/all_pokemon.ast.gql.dart
- gql_example_flutter/lib/src/pokemon_detail/pokemon_detail.ast.gql.dart
- build AST only for the definitions in the current file
- add definitions from imported files
- implement custom import allocator
> use SourceNode in AST builder

- gql_build/lib/src/data_builder.dart
- gql_build/lib/src/enum_builder.dart
- gql_build/lib/src/fragment_builder.dart
- gql_build/lib/src/input_builder.dart
- gql_build/lib/src/op_builder.dart
- gql_build/lib/src/req_builder.dart
- gql_build/lib/src/scalar_builder.dart
- gql_build/lib/src/schema_builder.dart
- gql_build/lib/src/var_builder.dart
- gql_code_builder/lib/data.dart
- gql_code_builder/lib/enum.dart
- gql_code_builder/lib/fragment.dart
- gql_code_builder/lib/input.dart
- gql_code_builder/lib/op.dart
- gql_code_builder/lib/req.dart
- gql_code_builder/lib/scalar.dart
- gql_code_builder/lib/schema.dart
- gql_code_builder/lib/var.dart
- flatten source node at code builder
> flatten source node at code builder

- gql/lib/src/validation/rules/unique_argument_names.dart
- gql/lib/src/validation/validator.dart
- gql/test/validation/unique_argument_names_test.dart
> Add UniqueArgumentNames validator

- gql_build/CHANGELOG.md
- gql_build/pubspec.yaml
- gql_code_builder/CHANGELOG.md
- gql_code_builder/lib/src/operation/data.dart
- gql_code_builder/pubspec.yaml
closes https://github.com/gql-dart/gql/issues/62
> take care of nullable url

- gql_build/CHANGELOG.md
- gql_build/lib/gql_build.dart
- gql_build/lib/src/data_builder.dart
- gql_build/lib/src/req_builder.dart
- gql_build/lib/src/utils/writer.dart
- gql_build/lib/src/var_builder.dart
- gql_build/pubspec.yaml
- gql_code_builder/CHANGELOG.md
- gql_code_builder/lib/req.dart
- gql_code_builder/lib/src/operation/req.dart
- gql_code_builder/pubspec.yaml
> fix schema url bug

- gql_build/CHANGELOG.md
- gql_build/pubspec.yaml
- gql_code_builder/CHANGELOG.md
- gql_code_builder/lib/src/operation/var.dart
- gql_code_builder/lib/src/schema/enum.dart
- gql_code_builder/lib/src/schema/input.dart
- gql_code_builder/lib/src/schema/scalar.dart
- gql_code_builder/pubspec.yaml
- escape reserved and private names
> escape reserved and private names

- .github/workflows/dart.yml
- gql_example_build/bin/main.dart
- gql_example_cli_github/bin/local.dart
- gql_example_cli_github/bin/main.dart
- escape reserved and private names
> Actions on examples

- gql_example_build/lib/fragments/shape.ast.gql.dart
- gql_example_build/lib/fragments/shape.data.gql.dart
- gql_example_build/lib/fragments/shape.graphql
- gql_example_build/lib/fragments/shape.op.gql.dart
- gql_example_build/lib/fragments/shape.req.gql.dart
- gql_example_build/lib/fragments/shape.var.gql.dart
- gql_example_build/lib/schema.ast.gql.dart
- gql_example_build/lib/schema.graphql
- gql_example_build/pubspec.yaml
- gql_example_build/test/fragments/shape_test.dart
add example and test of the fragment builder functionality
It will be run on every PR.
> add generated code tests

- README.md
Changed the ``gql_client`` to be ``ferry`` and updated the link
> Update gql_client to ferry

- gql_http_link/CHANGELOG.md
- gql_http_link/lib/src/link.dart
- gql_http_link/pubspec.yaml
- gql_link/CHANGELOG.md
- gql_link/lib/src/exceptions.dart
gql_link: cover Context access exceptions
gql_http_link: cover IO exceptions and context access exceptions
> Link exception improvements

- README.md
I have implemented a clone of gql_http_link that works with dio as the http client.
> Add gql_dio_link to the list of users

- README.md
- gql/README.md
- gql_build/README.md
- gql_code_builder/README.md
- gql_dedupe_link/README.md
- gql_exec/README.md
- gql_http_link/README.md
- gql_link/README.md
- gql_pedantic/README.md
- gql_transform_link/README.md
- gql_websocket_link/README.md
- multipack/README.md
- adding badges
@micimize arranged repurposing of the graphql-flutter chat to a wider GraphQL Dart community chat. @comigor,@smkhalsa, you might be interested in joining as well.
> add badges and link to discord

- gql/lib/src/language/lexer.dart
- gql/test/lexer_test.dart
Closes https://github.com/gql-dart/gql/issues/99
> Properly consider "blank comments"

- links/gql_websocket_link/lib/src/link.dart
- links/gql_websocket_link/test/gql_websocket_link_test.dart
As described here (https://github.com/zino-app/graphql-flutter/issues/658), we need to apply the async initialPayload handling logic.
> Apply the async initialPayload handling logic

- links/gql_exec/lib/src/context.dart
- links/gql_exec/lib/src/error.dart
- links/gql_exec/lib/src/operation.dart
- links/gql_exec/lib/src/request.dart
- links/gql_exec/lib/src/response.dart
- links/gql_link/lib/src/exceptions.dart
Closes https://github.com/gql-dart/gql/issues/128
> Add toString to exceptions

- links/gql_http_link/test/gql_http_link_test.dart
prevent any future regressions in json serialization
> add test for all types

- codegen/end_to_end_test/build.yaml
- codegen/end_to_end_test/lib/custom_field.dart
- codegen/end_to_end_test/lib/custom_field_serializer.dart
- codegen/end_to_end_test/lib/graphql/schema.ast.gql.dart
- codegen/end_to_end_test/lib/graphql/schema.graphql
- codegen/end_to_end_test/lib/graphql/serializers.gql.dart
- codegen/end_to_end_test/lib/graphql/serializers.gql.g.dart
- codegen/end_to_end_test/lib/scalars/review_with_date.ast.gql.dart
- codegen/end_to_end_test/lib/scalars/review_with_date.data.gql.dart
- codegen/end_to_end_test/lib/scalars/review_with_date.data.gql.g.dart
- codegen/end_to_end_test/lib/scalars/review_with_date.graphql
- codegen/end_to_end_test/pubspec.yaml
- codegen/end_to_end_test/test/schema/scalars_test.dart
- codegen/gql_build/CHANGELOG.md
- codegen/gql_build/lib/gql_build.dart
- codegen/gql_build/lib/src/serializer_builder.dart
- codegen/gql_build/pubspec.yaml
- codegen/gql_code_builder/CHANGELOG.md
- codegen/gql_code_builder/pubspec.yaml
> import type override references in serializers

- links/gql_websocket_link/CHANGELOG.md
- links/gql_websocket_link/lib/src/link.dart
- links/gql_websocket_link/pubspec.yaml
- links/gql_websocket_link/test/gql_websocket_link_test.dart
Related issue https://github.com/gql-dart/gql/issues/133
> Subscription stop command

- links/gql_websocket_link/CHANGELOG.md
- links/gql_websocket_link/lib/src/link.dart
- links/gql_websocket_link/pubspec.yaml
Related issue https://github.com/gql-dart/gql/issues/164
> Add channelGenerator constructor paramete

- links/gql_websocket_link/CHANGELOG.md
- links/gql_websocket_link/lib/src/link.dart
- links/gql_websocket_link/pubspec.yaml
- links/gql_websocket_link/test/gql_websocket_link_test.dart
Related issue https://github.com/gql-dart/gql/issues/176
> websocket link, customise json encoder & decode

- README.md
In response to issue https://github.com/gql-dart/gql/issues/200
> fix links on README

- codegen/end_to_end_test/pubspec.yaml
- codegen/gql_build/lib/src/allocators/gql_allocator.dart
- codegen/gql_build/lib/src/allocators/pick_allocator.dart
- codegen/gql_build/lib/src/serializer_builder.dart
- codegen/gql_build/lib/src/utils/writer.dart
- codegen/gql_build/pubspec.yaml
- codegen/gql_code_builder/lib/ast.dart
- codegen/gql_code_builder/lib/serializer.dart
- codegen/gql_code_builder/lib/src/schema.dart
- codegen/gql_code_builder/pubspec.yaml
> Upgrade code_builder & build_runner to null safety

- codegen/gql_code_builder/lib/src/common.dart
> Escape "update" in codegen

- codegen/gql_code_builder/lib/src/common.dart
closes https://github.com/gql-dart/gql/issues/248
> Add "values" to reserved words

- links/gql_dio_link/.gitignore
- links/gql_dio_link/CHANGELOG.md
- links/gql_dio_link/lib/src/_utils.dart
- links/gql_dio_link/lib/src/dio_link.dart
- links/gql_dio_link/pubspec.yaml
- links/gql_dio_link/test/multipart_upload_test.dart
now dio_link should be able to handle `MultipartFile` files
Closes #169
> [dio link] Add support for file upload

- codegen/gql_code_builder/lib/src/built_class.dart
- codegen/gql_code_builder/lib/src/common.dart
- codegen/gql_code_builder/lib/src/operation/data.dart
`gql_code_builder` was not adding the `@override` annotation where applicable, causing `flutter analyze` to complain.
> fix(gql_code_builder): add @override annotation

- .github/workflows/dart.yml
in order to use the latest graphviz package. the one from ubuntu is outdated and seems to be broken
> use macos to generate svg

- codegen/gql_build/CHANGELOG.md
- codegen/gql_build/pubspec.yaml
Fixes https://github.com/gql-dart/gql/issues/341
> fix: Upgrade `gql_code_builder` for `gql_build`

- links/gql_websocket_link/pubspec.yaml
fix dependency version mismatch with other packages.
> rxdart updated to latest version

- links/gql_websocket_link/lib/src/link.dart
Fix https://github.com/gql-dart/gql/issues/294
> _defaultGraphQLSocketMessageDecoder to return non-nullable Map

- codegen/gql_build/lib/src/serializer_builder.dart
- codegen/gql_build/pubspec.yaml
- codegen/gql_code_builder/pubspec.yaml
Set version constraints for analyzer to `>=4.6.0 <6.0.0`
> chore: updated analyzer

- links/gql_dio_link/lib/src/dio_link.dart
- links/gql_exec/lib/gql_exec.dart
- links/gql_http_link/lib/src/link.dart
This fixes https://github.com/gql-dart/gql/issues/361 for the most part
> Share code between http and dio link

- links/gql_dio_link/lib/gql_dio_link.dart
- links/gql_dio_link/lib/src/dio_link.dart
- links/gql_dio_link/pubspec.yaml
- links/gql_dio_link/test/gql_dio_link_test.dart
- links/gql_exec/lib/src/http.dart
- links/gql_exec/pubspec.yaml
- links/gql_http_link/lib/gql_http_link.dart
- links/gql_http_link/lib/src/link.dart
- links/gql_http_link/pubspec.yaml
> fix: use typedefs instead of subclasses for base contexts for http bases links

- links/gql_dio_link/lib/src/dio_link.dart
- links/gql_dio_link/lib/src/exceptions.dart
- links/gql_http_link/lib/src/exceptions.dart
- links/gql_http_link/lib/src/link.dart
- links/gql_link/lib/src/exceptions.dart
This adds the ability to add the http status code to a server exception.
> Add status code to ServerException

- codegen/gql_code_builder/CHANGELOG.md
- codegen/gql_code_builder/pubspec.yaml
- links/gql_dio_link/CHANGELOG.md
- docs(gql_dio_link): support dio 5.0.0
- docs(gql_code_gen: update readme
- chore(gql_code_builder): bump version
> prepare release

- links/gql_exec/lib/gql_exec.dart
- links/gql_exec/lib/src/operation_operationtype_extension.dart
- links/gql_exec/test/get_operation_type_test.dart
> feat(gql_exec): add getOperationType() to Operation via extension method

- README.md
This removes a couple of deprecated third party libraries from the readme
> Remove deprecated libraries from README

- links/gql_websocket_link/README.md
> docs(gql_websocket_link): add more documentation about the websocket subprotocols

- links/gql_websocket_link/pubspec.yaml
Update `uuid` package closes #439
> Update uuid package

- codegen/gql_code_builder/lib/serializer.dart
- codegen/gql_code_builder/pubspec.yaml
- **feat(gql_code_builder): allow external schema import**
- **bump version**
> external schema import

- links/gql_error_link/README.md
> Fix link in gql_error_link/README.md

- links/gql_websocket_link/pubspec.yaml
Would like to use with another package that requires rxdart 0.28.0.
> Bump to be compatible with rxDart 0.28.0

- codegen/gql_build/pubspec.yaml
- codegen/gql_code_builder/pubspec.yaml
- **feat(gql_build): bump deps**
- **feat(gql_code_builder): bump deps**
> depsupdate2
